---
  - name: create mount dir
    file: path="{{ item.value }}/es" state=directory recurse=yes 
    with_dict: "{{ disks }}"

#  - name: umount datanode disks
#    mount:  path="{{ item.value }}" state=absent
#    with_dict: "{{ disks }}"

  - name: u
    parted: device={{ item.key }} number=1 state=present
    with_dict: "{{ disks }}"


  - name: format datanode disks
    filesystem: fstype=ext4 dev="{{ item.key }}" force=true
    with_dict: "{{ disks }}"

  - name: mount datanode disks
    mount:   path="{{ item.value }}" src="{{ item.key }}"     fstype=ext4 opts="defaults,noatime,nobarrier" state=mounted
    with_dict: "{{ disks }}"
