---
  - name: change limits.conf hard
    lineinfile: path=/etc/security/limits.conf regexp='\* sort nofile [0-9]+' backrefs=no line='* soft nofile 65535'
  - name: change limits.conf soft 
    lineinfile: path=/etc/security/limits.conf regexp='\* hard nofile [0-9]+' backrefs=no line='* hard nofile 65535'
  - name: Ulimit change
    shell: ulimit -SHn 655360

  - name: install base soft
    apt: name={{ item }} state=latest update_cache=yes 
    with_items:
        - atop
        - telnet 
        - iftop 
        - tcpdump 
        - sendmail 
        - traceroute 
        - mtr 
        - wget 
        - vim
        - dstat 
        - screen 
        - rsync 
        - zip 
        - unzip 
        - tree
        - nmap
        - lrzsz 
        - dos2unix 
        - lsof
  - name: set vm.swappiness
    sysctl: name=vm.swappiness value=0 state=present
  - name: update timezone 
    shell: cp /usr/share/zoneinfo/Asia/Shanghai   /etc/localtime 
    shell: sed -i 's@Etc/UTC@Asia/Shanghai@g'  /etc/timezone
    shell: sed -i 's@US/Eastern@Asia/Shanghai@g'  /etc/timezone &&  sed -i 's@America/New_York/Shanghai@g' /etc/timezone
    ignore_errors: True 
 
#  - name: init timezone
#    file: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime state=link  

  - name: supported.d |ubuntu 14.04
    shell: echo "en_US.UTF-8 UTF-8" |sudo tee /var/lib/locales/supported.d/local &&  echo "zh_CN.UTF-8 UTF-8" |sudo tee -a /var/lib/locales/supported.d/local
    when: ansible_os_family == "Debian" and ansible_lsb.major_release|int == 14 
#    register: result1
  
#  - name: app message
#    debug: msg="{{ result1.stdout }}"

  - name: shutdown transparent hugepage
    shell: echo 'never' |sudo tee /sys/kernel/mm/transparent_hugepage/enabled && echo never |sudo tee /sys/kernel/mm/transparent_hugepage/defrag
    ignore_errors: True    
  
  - name: add transparent hugepage rc.local
    lineinfile: dest=/etc/rc.local line={{ item }}  
    with_items: 
        - echo never > /sys/kernel/mm/transparent_hugepage/enabled
        - echo never > /sys/kernel/mm/transparent_hugepage/defrag   
    
  - name: change ssh port
    lineinfile: dest=/etc/ssh/sshd_config regexp='Port 22' backrefs=yes line='Port 8130'
    
  - name: Restart sshd
    service: name=ssh state=restarted enabled=yes
 
  - name: add new apt-source ubuntu16
    copy: src=sources.list.16 dest=/etc/apt/sources.list  mode=0644 owner=root group=root backup=yes
    when: ansible_os_family == "Debian" and ansible_lsb.major_release|int == 16

  - name: add new apt-source|ubuntu14
    copy: src=sources.list.14 dest=/etc/apt/sources.list  mode=0644 owner=root group=root backup=yes
    when: ansible_os_family == "Debian" and ansible_lsb.major_release|int == 14

  - name:  apt update
    apt: update_cache=yes state=present
  

  - name: change passwd
    user: name={{ username }}  password={{ user_password | password_hash('sha512') }} update_password=always

  - name: copy history profile file
    copy: src=history.sh  dest=/etc/profile.d/history.sh backup=yes

  - name: change history profile  
    shell: sh  /etc/profile.d/history.sh 
    ignore_errors: True 
 
  - name: change hosts
    copy: src=hosts dest=/etc/hosts backup=yes 

  - name: disk
    include: ./../../init_disk/tasks/main.yml
    when: ansible_hostname == "mode03"

#  - name: reboot system
#    command: shutdown -r now 
